FROM node:16-alpine as builder

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD [ "npm","run","start"]#

FROM nginx
#bu şekilde diyoruz ki, sen o bir önceki builde git ve oradaki app/buildi al, daha sonra nginxdeki klasöre koy
#copy'ye bir --from= flagi vererek yolumuza devam ediyoruz
COPY --from=builder /app/build  /usr/share/nginx/html